/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PublicTD[1];
new PlayerText:PlayerTD[MAX_PLAYERS][4];
new PlayerText:formainui[MAX_PLAYERS];
new PlayerText:uppermainui[MAX_PLAYERS];
new PlayerText:header[MAX_PLAYERS];
new PlayerText:seperator[MAX_PLAYERS];
new PlayerText:timeAlive[MAX_PLAYERS];
new PlayerText:aliveTimeTimer[MAX_PLAYERS];
new PlayerText:zombiesKilled[MAX_PLAYERS];
new PlayerText:zombiesKilledCounter[MAX_PLAYERS];
new PlayerText:weaponHolder[MAX_PLAYERS];

//Textdraws
PublicTD[0] = TextDrawCreate(554.000000, 20.000000, "XomoX_Test");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.320833, 1.500000);
TextDrawTextSize(PublicTD[0], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 0);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);


//Player Textdraws
formainui[playerid] = CreatePlayerTextDraw(playerid, 554.000000, 18.000000, "_");
PlayerTextDrawFont(playerid, formainui[playerid], 1);
PlayerTextDrawLetterSize(playerid, formainui[playerid], 0.583333, 14.350014);
PlayerTextDrawTextSize(playerid, formainui[playerid], 304.000000, 152.500000);
PlayerTextDrawSetOutline(playerid, formainui[playerid], 0);
PlayerTextDrawSetShadow(playerid, formainui[playerid], 0);
PlayerTextDrawAlignment(playerid, formainui[playerid], 2);
PlayerTextDrawColor(playerid, formainui[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, formainui[playerid], 255);
PlayerTextDrawBoxColor(playerid, formainui[playerid], 255);
PlayerTextDrawUseBox(playerid, formainui[playerid], 1);
PlayerTextDrawSetProportional(playerid, formainui[playerid], 1);
PlayerTextDrawSetSelectable(playerid, formainui[playerid], 0);

uppermainui[playerid] = CreatePlayerTextDraw(playerid, 554.000000, 23.000000, "_");
PlayerTextDrawFont(playerid, uppermainui[playerid], 1);
PlayerTextDrawLetterSize(playerid, uppermainui[playerid], 0.600000, 13.100009);
PlayerTextDrawTextSize(playerid, uppermainui[playerid], 362.500000, 142.500000);
PlayerTextDrawSetOutline(playerid, uppermainui[playerid], 1);
PlayerTextDrawSetShadow(playerid, uppermainui[playerid], 0);
PlayerTextDrawAlignment(playerid, uppermainui[playerid], 2);
PlayerTextDrawColor(playerid, uppermainui[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, uppermainui[playerid], 255);
PlayerTextDrawBoxColor(playerid, uppermainui[playerid], -168436601);
PlayerTextDrawUseBox(playerid, uppermainui[playerid], 1);
PlayerTextDrawSetProportional(playerid, uppermainui[playerid], 1);
PlayerTextDrawSetSelectable(playerid, uppermainui[playerid], 0);

header[playerid] = CreatePlayerTextDraw(playerid, 551.000000, 2.000000, "discord.gg/samp");
PlayerTextDrawFont(playerid, header[playerid], 1);
PlayerTextDrawLetterSize(playerid, header[playerid], 0.295832, 1.200000);
PlayerTextDrawTextSize(playerid, header[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, header[playerid], 1);
PlayerTextDrawSetShadow(playerid, header[playerid], 0);
PlayerTextDrawAlignment(playerid, header[playerid], 1);
PlayerTextDrawColor(playerid, header[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, header[playerid], 255);
PlayerTextDrawBoxColor(playerid, header[playerid], 50);
PlayerTextDrawUseBox(playerid, header[playerid], 0);
PlayerTextDrawSetProportional(playerid, header[playerid], 1);
PlayerTextDrawSetSelectable(playerid, header[playerid], 0);

seperator[playerid] = CreatePlayerTextDraw(playerid, 554.000000, 33.000000, "-------------------------------");
PlayerTextDrawFont(playerid, seperator[playerid], 1);
PlayerTextDrawLetterSize(playerid, seperator[playerid], 0.295832, 0.550000);
PlayerTextDrawTextSize(playerid, seperator[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, seperator[playerid], 1);
PlayerTextDrawSetShadow(playerid, seperator[playerid], 0);
PlayerTextDrawAlignment(playerid, seperator[playerid], 2);
PlayerTextDrawColor(playerid, seperator[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, seperator[playerid], 255);
PlayerTextDrawBoxColor(playerid, seperator[playerid], 50);
PlayerTextDrawUseBox(playerid, seperator[playerid], 0);
PlayerTextDrawSetProportional(playerid, seperator[playerid], 1);
PlayerTextDrawSetSelectable(playerid, seperator[playerid], 0);

timeAlive[playerid] = CreatePlayerTextDraw(playerid, 535.000000, 39.000000, "Time Alive:");
PlayerTextDrawFont(playerid, timeAlive[playerid], 1);
PlayerTextDrawLetterSize(playerid, timeAlive[playerid], 0.258332, 1.199998);
PlayerTextDrawTextSize(playerid, timeAlive[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, timeAlive[playerid], 1);
PlayerTextDrawSetShadow(playerid, timeAlive[playerid], 0);
PlayerTextDrawAlignment(playerid, timeAlive[playerid], 3);
PlayerTextDrawColor(playerid, timeAlive[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, timeAlive[playerid], 255);
PlayerTextDrawBoxColor(playerid, timeAlive[playerid], 50);
PlayerTextDrawUseBox(playerid, timeAlive[playerid], 0);
PlayerTextDrawSetProportional(playerid, timeAlive[playerid], 1);
PlayerTextDrawSetSelectable(playerid, timeAlive[playerid], 0);

aliveTimeTimer[playerid] = CreatePlayerTextDraw(playerid, 569.000000, 39.000000, "00:00:00");
PlayerTextDrawFont(playerid, aliveTimeTimer[playerid], 1);
PlayerTextDrawLetterSize(playerid, aliveTimeTimer[playerid], 0.304165, 1.199000);
PlayerTextDrawTextSize(playerid, aliveTimeTimer[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, aliveTimeTimer[playerid], 1);
PlayerTextDrawSetShadow(playerid, aliveTimeTimer[playerid], 0);
PlayerTextDrawAlignment(playerid, aliveTimeTimer[playerid], 1);
PlayerTextDrawColor(playerid, aliveTimeTimer[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, aliveTimeTimer[playerid], 255);
PlayerTextDrawBoxColor(playerid, aliveTimeTimer[playerid], 50);
PlayerTextDrawUseBox(playerid, aliveTimeTimer[playerid], 0);
PlayerTextDrawSetProportional(playerid, aliveTimeTimer[playerid], 1);
PlayerTextDrawSetSelectable(playerid, aliveTimeTimer[playerid], 0);

zombiesKilled[playerid] = CreatePlayerTextDraw(playerid, 542.000000, 52.000000, "Zombies Killed:");
PlayerTextDrawFont(playerid, zombiesKilled[playerid], 1);
PlayerTextDrawLetterSize(playerid, zombiesKilled[playerid], 0.224665, 1.199000);
PlayerTextDrawTextSize(playerid, zombiesKilled[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, zombiesKilled[playerid], 1);
PlayerTextDrawSetShadow(playerid, zombiesKilled[playerid], 0);
PlayerTextDrawAlignment(playerid, zombiesKilled[playerid], 3);
PlayerTextDrawColor(playerid, zombiesKilled[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, zombiesKilled[playerid], 255);
PlayerTextDrawBoxColor(playerid, zombiesKilled[playerid], 50);
PlayerTextDrawUseBox(playerid, zombiesKilled[playerid], 0);
PlayerTextDrawSetProportional(playerid, zombiesKilled[playerid], 1);
PlayerTextDrawSetSelectable(playerid, zombiesKilled[playerid], 0);

zombiesKilledCounter[playerid] = CreatePlayerTextDraw(playerid, 583.000000, 51.000000, "100");
PlayerTextDrawFont(playerid, zombiesKilledCounter[playerid], 1);
PlayerTextDrawLetterSize(playerid, zombiesKilledCounter[playerid], 0.303999, 1.199000);
PlayerTextDrawTextSize(playerid, zombiesKilledCounter[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, zombiesKilledCounter[playerid], 1);
PlayerTextDrawSetShadow(playerid, zombiesKilledCounter[playerid], 0);
PlayerTextDrawAlignment(playerid, zombiesKilledCounter[playerid], 1);
PlayerTextDrawColor(playerid, zombiesKilledCounter[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, zombiesKilledCounter[playerid], 255);
PlayerTextDrawBoxColor(playerid, zombiesKilledCounter[playerid], 50);
PlayerTextDrawUseBox(playerid, zombiesKilledCounter[playerid], 0);
PlayerTextDrawSetProportional(playerid, zombiesKilledCounter[playerid], 1);
PlayerTextDrawSetSelectable(playerid, zombiesKilledCounter[playerid], 0);

PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 518.000000, 64.000000, "Murders:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.224665, 1.199000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 3);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 583.000000, 64.000000, "100");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.303999, 1.199000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 554.000000, 124.000000, "-------------------------------");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.295832, 0.550000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 140.000000, 376.000000, "Reloot:~n~~g~00:00");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.266665, 1.500000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

weaponHolder[playerid] = CreatePlayerTextDraw(playerid, 608.000000, 128.000000, "Weapon: M4 - 300");
PlayerTextDrawFont(playerid, weaponHolder[playerid], 1);
PlayerTextDrawLetterSize(playerid, weaponHolder[playerid], 0.350000, 1.500000);
PlayerTextDrawTextSize(playerid, weaponHolder[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, weaponHolder[playerid], 1);
PlayerTextDrawSetShadow(playerid, weaponHolder[playerid], 0);
PlayerTextDrawAlignment(playerid, weaponHolder[playerid], 3);
PlayerTextDrawColor(playerid, weaponHolder[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, weaponHolder[playerid], 255);
PlayerTextDrawBoxColor(playerid, weaponHolder[playerid], 50);
PlayerTextDrawUseBox(playerid, weaponHolder[playerid], 0);
PlayerTextDrawSetProportional(playerid, weaponHolder[playerid], 1);
PlayerTextDrawSetSelectable(playerid, weaponHolder[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
