/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:backPlating[MAX_PLAYERS];
new PlayerText:playerSkin[MAX_PLAYERS];
new PlayerText:hungerBox[MAX_PLAYERS];
new PlayerText:hungerIcon[MAX_PLAYERS];
new PlayerText:hunger[MAX_PLAYERS];
new PlayerText:thirstBox[MAX_PLAYERS];
new PlayerText:thirstIcon[MAX_PLAYERS];
new PlayerText:thirst[MAX_PLAYERS];
new PlayerText:humanityBox[MAX_PLAYERS];
new PlayerText:humanityIcon[MAX_PLAYERS];
new PlayerText:humanity[MAX_PLAYERS];
new PlayerText:coinsBox[MAX_PLAYERS];
new PlayerText:coinsIcon[MAX_PLAYERS];
new PlayerText:coins[MAX_PLAYERS];
new PlayerText:map[MAX_PLAYERS];
new PlayerText:safeZone[MAX_PLAYERS];
new PlayerText:informationText[MAX_PLAYERS];
new PlayerText:playerName[MAX_PLAYERS];

//Textdraws

//Player Textdraws
backPlating[playerid] = CreatePlayerTextDraw(playerid, 315.000000, 89.000000, "_");
PlayerTextDrawFont(playerid, backPlating[playerid], 1);
PlayerTextDrawLetterSize(playerid, backPlating[playerid], 0.600000, 29.300003);
PlayerTextDrawTextSize(playerid, backPlating[playerid], 348.500000, 474.000000);
PlayerTextDrawSetOutline(playerid, backPlating[playerid], 1);
PlayerTextDrawSetShadow(playerid, backPlating[playerid], 0);
PlayerTextDrawAlignment(playerid, backPlating[playerid], 2);
PlayerTextDrawColor(playerid, backPlating[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, backPlating[playerid], 255);
PlayerTextDrawBoxColor(playerid, backPlating[playerid], -1962934017);
PlayerTextDrawUseBox(playerid, backPlating[playerid], 1);
PlayerTextDrawSetProportional(playerid, backPlating[playerid], 1);
PlayerTextDrawSetSelectable(playerid, backPlating[playerid], 0);

playerSkin[playerid] = CreatePlayerTextDraw(playerid, 97.000000, 125.000000, "Preview_Model");
PlayerTextDrawFont(playerid, playerSkin[playerid], 5);
PlayerTextDrawLetterSize(playerid, playerSkin[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, playerSkin[playerid], 112.500000, 198.500000);
PlayerTextDrawSetOutline(playerid, playerSkin[playerid], 0);
PlayerTextDrawSetShadow(playerid, playerSkin[playerid], 0);
PlayerTextDrawAlignment(playerid, playerSkin[playerid], 1);
PlayerTextDrawColor(playerid, playerSkin[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, playerSkin[playerid], 125);
PlayerTextDrawBoxColor(playerid, playerSkin[playerid], -16776961);
PlayerTextDrawUseBox(playerid, playerSkin[playerid], 0);
PlayerTextDrawSetProportional(playerid, playerSkin[playerid], 1);
PlayerTextDrawSetSelectable(playerid, playerSkin[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, playerSkin[playerid], 50);
PlayerTextDrawSetPreviewRot(playerid, playerSkin[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, playerSkin[playerid], 1, 1);

hungerBox[playerid] = CreatePlayerTextDraw(playerid, 250.000000, 128.000000, "_");
PlayerTextDrawFont(playerid, hungerBox[playerid], 1);
PlayerTextDrawLetterSize(playerid, hungerBox[playerid], 0.600000, 10.300003);
PlayerTextDrawTextSize(playerid, hungerBox[playerid], 298.500000, 75.000000);
PlayerTextDrawSetOutline(playerid, hungerBox[playerid], 1);
PlayerTextDrawSetShadow(playerid, hungerBox[playerid], 0);
PlayerTextDrawAlignment(playerid, hungerBox[playerid], 2);
PlayerTextDrawColor(playerid, hungerBox[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, hungerBox[playerid], 255);
PlayerTextDrawBoxColor(playerid, hungerBox[playerid], 135);
PlayerTextDrawUseBox(playerid, hungerBox[playerid], 1);
PlayerTextDrawSetProportional(playerid, hungerBox[playerid], 1);
PlayerTextDrawSetSelectable(playerid, hungerBox[playerid], 0);

hungerIcon[playerid] = CreatePlayerTextDraw(playerid, 238.000000, 147.000000, "HUD:radar_burgershot");
PlayerTextDrawFont(playerid, hungerIcon[playerid], 4);
PlayerTextDrawLetterSize(playerid, hungerIcon[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, hungerIcon[playerid], 22.000000, 32.000000);
PlayerTextDrawSetOutline(playerid, hungerIcon[playerid], 1);
PlayerTextDrawSetShadow(playerid, hungerIcon[playerid], 0);
PlayerTextDrawAlignment(playerid, hungerIcon[playerid], 1);
PlayerTextDrawColor(playerid, hungerIcon[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, hungerIcon[playerid], 255);
PlayerTextDrawBoxColor(playerid, hungerIcon[playerid], 50);
PlayerTextDrawUseBox(playerid, hungerIcon[playerid], 1);
PlayerTextDrawSetProportional(playerid, hungerIcon[playerid], 1);
PlayerTextDrawSetSelectable(playerid, hungerIcon[playerid], 0);

hunger[playerid] = CreatePlayerTextDraw(playerid, 250.000000, 193.000000, "500");
PlayerTextDrawFont(playerid, hunger[playerid], 3);
PlayerTextDrawLetterSize(playerid, hunger[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, hunger[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, hunger[playerid], 1);
PlayerTextDrawSetShadow(playerid, hunger[playerid], 0);
PlayerTextDrawAlignment(playerid, hunger[playerid], 2);
PlayerTextDrawColor(playerid, hunger[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, hunger[playerid], 255);
PlayerTextDrawBoxColor(playerid, hunger[playerid], 50);
PlayerTextDrawUseBox(playerid, hunger[playerid], 0);
PlayerTextDrawSetProportional(playerid, hunger[playerid], 1);
PlayerTextDrawSetSelectable(playerid, hunger[playerid], 0);

thirstBox[playerid] = CreatePlayerTextDraw(playerid, 250.000000, 228.000000, "_");
PlayerTextDrawFont(playerid, thirstBox[playerid], 1);
PlayerTextDrawLetterSize(playerid, thirstBox[playerid], 0.600000, 10.300003);
PlayerTextDrawTextSize(playerid, thirstBox[playerid], 298.500000, 75.000000);
PlayerTextDrawSetOutline(playerid, thirstBox[playerid], 1);
PlayerTextDrawSetShadow(playerid, thirstBox[playerid], 0);
PlayerTextDrawAlignment(playerid, thirstBox[playerid], 2);
PlayerTextDrawColor(playerid, thirstBox[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, thirstBox[playerid], 255);
PlayerTextDrawBoxColor(playerid, thirstBox[playerid], 135);
PlayerTextDrawUseBox(playerid, thirstBox[playerid], 1);
PlayerTextDrawSetProportional(playerid, thirstBox[playerid], 1);
PlayerTextDrawSetSelectable(playerid, thirstBox[playerid], 0);

thirstIcon[playerid] = CreatePlayerTextDraw(playerid, 238.000000, 243.000000, "HUD:radar_datedrink");
PlayerTextDrawFont(playerid, thirstIcon[playerid], 4);
PlayerTextDrawLetterSize(playerid, thirstIcon[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, thirstIcon[playerid], 22.000000, 32.000000);
PlayerTextDrawSetOutline(playerid, thirstIcon[playerid], 1);
PlayerTextDrawSetShadow(playerid, thirstIcon[playerid], 0);
PlayerTextDrawAlignment(playerid, thirstIcon[playerid], 1);
PlayerTextDrawColor(playerid, thirstIcon[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, thirstIcon[playerid], 255);
PlayerTextDrawBoxColor(playerid, thirstIcon[playerid], 50);
PlayerTextDrawUseBox(playerid, thirstIcon[playerid], 1);
PlayerTextDrawSetProportional(playerid, thirstIcon[playerid], 1);
PlayerTextDrawSetSelectable(playerid, thirstIcon[playerid], 0);

thirst[playerid] = CreatePlayerTextDraw(playerid, 250.000000, 288.000000, "500");
PlayerTextDrawFont(playerid, thirst[playerid], 3);
PlayerTextDrawLetterSize(playerid, thirst[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, thirst[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, thirst[playerid], 1);
PlayerTextDrawSetShadow(playerid, thirst[playerid], 0);
PlayerTextDrawAlignment(playerid, thirst[playerid], 2);
PlayerTextDrawColor(playerid, thirst[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, thirst[playerid], 255);
PlayerTextDrawBoxColor(playerid, thirst[playerid], 50);
PlayerTextDrawUseBox(playerid, thirst[playerid], 0);
PlayerTextDrawSetProportional(playerid, thirst[playerid], 1);
PlayerTextDrawSetSelectable(playerid, thirst[playerid], 0);

humanityBox[playerid] = CreatePlayerTextDraw(playerid, 330.000000, 128.000000, "_");
PlayerTextDrawFont(playerid, humanityBox[playerid], 1);
PlayerTextDrawLetterSize(playerid, humanityBox[playerid], 0.600000, 10.300003);
PlayerTextDrawTextSize(playerid, humanityBox[playerid], 298.500000, 75.000000);
PlayerTextDrawSetOutline(playerid, humanityBox[playerid], 1);
PlayerTextDrawSetShadow(playerid, humanityBox[playerid], 0);
PlayerTextDrawAlignment(playerid, humanityBox[playerid], 2);
PlayerTextDrawColor(playerid, humanityBox[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, humanityBox[playerid], 255);
PlayerTextDrawBoxColor(playerid, humanityBox[playerid], 135);
PlayerTextDrawUseBox(playerid, humanityBox[playerid], 1);
PlayerTextDrawSetProportional(playerid, humanityBox[playerid], 1);
PlayerTextDrawSetSelectable(playerid, humanityBox[playerid], 0);

humanityIcon[playerid] = CreatePlayerTextDraw(playerid, 319.000000, 147.000000, "ld_tatt:4rip");
PlayerTextDrawFont(playerid, humanityIcon[playerid], 4);
PlayerTextDrawLetterSize(playerid, humanityIcon[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, humanityIcon[playerid], 22.000000, 32.000000);
PlayerTextDrawSetOutline(playerid, humanityIcon[playerid], 1);
PlayerTextDrawSetShadow(playerid, humanityIcon[playerid], 0);
PlayerTextDrawAlignment(playerid, humanityIcon[playerid], 1);
PlayerTextDrawColor(playerid, humanityIcon[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, humanityIcon[playerid], 255);
PlayerTextDrawBoxColor(playerid, humanityIcon[playerid], 50);
PlayerTextDrawUseBox(playerid, humanityIcon[playerid], 1);
PlayerTextDrawSetProportional(playerid, humanityIcon[playerid], 1);
PlayerTextDrawSetSelectable(playerid, humanityIcon[playerid], 0);

humanity[playerid] = CreatePlayerTextDraw(playerid, 330.000000, 192.000000, "500");
PlayerTextDrawFont(playerid, humanity[playerid], 3);
PlayerTextDrawLetterSize(playerid, humanity[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, humanity[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, humanity[playerid], 1);
PlayerTextDrawSetShadow(playerid, humanity[playerid], 0);
PlayerTextDrawAlignment(playerid, humanity[playerid], 2);
PlayerTextDrawColor(playerid, humanity[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, humanity[playerid], 255);
PlayerTextDrawBoxColor(playerid, humanity[playerid], 50);
PlayerTextDrawUseBox(playerid, humanity[playerid], 0);
PlayerTextDrawSetProportional(playerid, humanity[playerid], 1);
PlayerTextDrawSetSelectable(playerid, humanity[playerid], 0);

coinsBox[playerid] = CreatePlayerTextDraw(playerid, 330.000000, 228.000000, "_");
PlayerTextDrawFont(playerid, coinsBox[playerid], 1);
PlayerTextDrawLetterSize(playerid, coinsBox[playerid], 0.600000, 10.300003);
PlayerTextDrawTextSize(playerid, coinsBox[playerid], 298.500000, 75.000000);
PlayerTextDrawSetOutline(playerid, coinsBox[playerid], 1);
PlayerTextDrawSetShadow(playerid, coinsBox[playerid], 0);
PlayerTextDrawAlignment(playerid, coinsBox[playerid], 2);
PlayerTextDrawColor(playerid, coinsBox[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, coinsBox[playerid], 255);
PlayerTextDrawBoxColor(playerid, coinsBox[playerid], 135);
PlayerTextDrawUseBox(playerid, coinsBox[playerid], 1);
PlayerTextDrawSetProportional(playerid, coinsBox[playerid], 1);
PlayerTextDrawSetSelectable(playerid, coinsBox[playerid], 0);

coinsIcon[playerid] = CreatePlayerTextDraw(playerid, 319.000000, 247.000000, "HUD:radar_cash");
PlayerTextDrawFont(playerid, coinsIcon[playerid], 4);
PlayerTextDrawLetterSize(playerid, coinsIcon[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, coinsIcon[playerid], 22.000000, 32.000000);
PlayerTextDrawSetOutline(playerid, coinsIcon[playerid], 1);
PlayerTextDrawSetShadow(playerid, coinsIcon[playerid], 0);
PlayerTextDrawAlignment(playerid, coinsIcon[playerid], 1);
PlayerTextDrawColor(playerid, coinsIcon[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, coinsIcon[playerid], 255);
PlayerTextDrawBoxColor(playerid, coinsIcon[playerid], 50);
PlayerTextDrawUseBox(playerid, coinsIcon[playerid], 1);
PlayerTextDrawSetProportional(playerid, coinsIcon[playerid], 1);
PlayerTextDrawSetSelectable(playerid, coinsIcon[playerid], 0);

coins[playerid] = CreatePlayerTextDraw(playerid, 330.000000, 288.000000, "500");
PlayerTextDrawFont(playerid, coins[playerid], 3);
PlayerTextDrawLetterSize(playerid, coins[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, coins[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, coins[playerid], 1);
PlayerTextDrawSetShadow(playerid, coins[playerid], 0);
PlayerTextDrawAlignment(playerid, coins[playerid], 2);
PlayerTextDrawColor(playerid, coins[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, coins[playerid], 255);
PlayerTextDrawBoxColor(playerid, coins[playerid], 50);
PlayerTextDrawUseBox(playerid, coins[playerid], 0);
PlayerTextDrawSetProportional(playerid, coins[playerid], 1);
PlayerTextDrawSetSelectable(playerid, coins[playerid], 0);

map[playerid] = CreatePlayerTextDraw(playerid, 372.000000, 126.000000, "samaps:map");
PlayerTextDrawFont(playerid, map[playerid], 4);
PlayerTextDrawLetterSize(playerid, map[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, map[playerid], 176.500000, 197.500000);
PlayerTextDrawSetOutline(playerid, map[playerid], 1);
PlayerTextDrawSetShadow(playerid, map[playerid], 0);
PlayerTextDrawAlignment(playerid, map[playerid], 1);
PlayerTextDrawColor(playerid, map[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, map[playerid], 255);
PlayerTextDrawBoxColor(playerid, map[playerid], 50);
PlayerTextDrawUseBox(playerid, map[playerid], 1);
PlayerTextDrawSetProportional(playerid, map[playerid], 1);
PlayerTextDrawSetSelectable(playerid, map[playerid], 0);

safeZone[playerid] = CreatePlayerTextDraw(playerid, 384.000000, 272.000000, "HUD:radar_crash1");
PlayerTextDrawFont(playerid, safeZone[playerid], 4);
PlayerTextDrawLetterSize(playerid, safeZone[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, safeZone[playerid], 12.500000, 9.500000);
PlayerTextDrawSetOutline(playerid, safeZone[playerid], 1);
PlayerTextDrawSetShadow(playerid, safeZone[playerid], 0);
PlayerTextDrawAlignment(playerid, safeZone[playerid], 1);
PlayerTextDrawColor(playerid, safeZone[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, safeZone[playerid], 255);
PlayerTextDrawBoxColor(playerid, safeZone[playerid], 50);
PlayerTextDrawUseBox(playerid, safeZone[playerid], 1);
PlayerTextDrawSetProportional(playerid, safeZone[playerid], 1);
PlayerTextDrawSetSelectable(playerid, safeZone[playerid], 0);

informationText[playerid] = CreatePlayerTextDraw(playerid, 315.000000, 95.000000, "Informations");
PlayerTextDrawFont(playerid, informationText[playerid], 0);
PlayerTextDrawLetterSize(playerid, informationText[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, informationText[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, informationText[playerid], 1);
PlayerTextDrawSetShadow(playerid, informationText[playerid], 0);
PlayerTextDrawAlignment(playerid, informationText[playerid], 2);
PlayerTextDrawColor(playerid, informationText[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, informationText[playerid], 255);
PlayerTextDrawBoxColor(playerid, informationText[playerid], 50);
PlayerTextDrawUseBox(playerid, informationText[playerid], 0);
PlayerTextDrawSetProportional(playerid, informationText[playerid], 1);
PlayerTextDrawSetSelectable(playerid, informationText[playerid], 0);

playerName[playerid] = CreatePlayerTextDraw(playerid, 315.000000, 330.000000, "XomoX");
PlayerTextDrawFont(playerid, playerName[playerid], 3);
PlayerTextDrawLetterSize(playerid, playerName[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, playerName[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, playerName[playerid], 1);
PlayerTextDrawSetShadow(playerid, playerName[playerid], 0);
PlayerTextDrawAlignment(playerid, playerName[playerid], 2);
PlayerTextDrawColor(playerid, playerName[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, playerName[playerid], 255);
PlayerTextDrawBoxColor(playerid, playerName[playerid], 50);
PlayerTextDrawUseBox(playerid, playerName[playerid], 0);
PlayerTextDrawSetProportional(playerid, playerName[playerid], 1);
PlayerTextDrawSetSelectable(playerid, playerName[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
